### ISSUE TITLE
`utils/JsonMap`: superobject for API calls and return values

### ISSUE THREAD

**Issue by sammdu** [TLI-Group-1/Backend#21]
Probably have an overloaded constructor method that can take:
* No arguments: represent with an empty HashMap internally
* A list of two items: Add list to HashMap where the first item of the list is the key and the second item the value 
* A HashMap object: copy and store
* A JSON string: convert to HashMap and store

Possibly inherit from HashMap class, or implement Map interface.

Look into the Jackson library for JSON manipulation.

**Comment by Shalev-Lifshitz** [comment]
Instead of 'a list of two items,' I'm going to be taking two arguments ('key' and 'value'). In this way, I can check the types of each and also ensure that we only get two items. ok?

**Comment by sammdu** [comment]
Also for this I'm thinking:
* `add()` method that works the same as the HashMap add
* `remove()` method that works the same as the HashMap remove
* `getMap()` returns a copy of the internal HashMap
* `getJSON()` returns a JSON String representing the internal HashMap
